### ISSUE TITLE
Server Error "no such function"

### ISSUE THREAD

**Issue by andreassteph** [michael-dev/dokuwikietherpadlite#22]
I have installed and configured the plugin. However I'm getting the error "no such function" as a js pop up. There is no error in the etherpad log and nothing in the dokuwiki log either. 
In the source it looks like the error handler forwards an error raised by something else, thus I wasn't able to track down were the error was raised initially.

I didn't manage to install the ep_iframeinsert plugin as it is neither in the npm repository or the etherpad lite library.

Is there any solution how to solve the error?
Could you help with any ideas on where this error is raised?

**Comment by XRayLP** [comment]
Hi @andreassteph, which Version of Etherpad Lite are you using? Because I had the same error with the new Version 1.8.7, because they deactivated two API calls "setPassword" and "isPasswordProtected". Passwords for Group Pads are no longer possible, but the Plugin in dokuwiki tries to check via the API call "isPasswordProtected" if the pad has a password protection. This fails with "no such function".
To fix the error you can manually deactivate the API call in the file lib/plugins/etherpadlite/action/etherpadlite.php by changing the line 201 to the following:
`$hasPassword = (bool) false; //($this->ep_instance->isPasswordProtected($pageid)->isPasswordProtected);`
This should deactivate the check if the pad is password protected, so the removed API calls are not used anymore. After doing this the plugin worked with the new Version.

**Comment by michael-dev** [comment]
Thanks, I ripped out the relevant code the relevant functionality. Would you mind testing the current master branch?

**Comment by andreassteph** [comment]
Thank you for the fast response that has solved the issue the integration seems to work now. I installed now directly from github master.
